# -*- coding: utf-8 -*-
"""MLP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iXF7DvYBpOQRN315JugjOZzOzAtOvjKz
"""

import torch

class linear_layer(torch.nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()
        self.reset_parameters(in_features, out_features)

    def forward(self, input):
        output = torch.sigmoid(torch.mm(input, self.weight))
        return output

    def reset_parameters(self, in_features, out_features):
        self.in_features = in_features
        self.out_features = out_features
        self.weight = torch.nn.Parameter(torch.randn(in_features, out_features))

# m = linear_layer(20, 30)
# input = torch.randn(128, 20)
# output = m(input)
# print(output.size())